include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    sort_child_properties_last: true
    use_key_in_widget_constructors: true

    # Riverpod
    avoid_dynamic_calls: false  # required for Firestore data maps

    # Errors
    avoid_empty_else: true
    avoid_relative_lib_imports: false
    cancel_subscriptions: true
    close_sinks: true
    no_duplicate_case_values: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - lib/firebase_options.dart
  errors:
    missing_required_param: error
    missing_return: error
    invalid_assignment: warning
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
