// lib/firebase_options.dart
//
// ─────────────────────────────────────────────────────────────────────────────
// IMPORTANT: This file is auto-generated by the FlutterFire CLI.
// DO NOT edit this file manually.
//
// SETUP STEPS:
//   1. Install FlutterFire CLI:
//        dart pub global activate flutterfire_cli
//
//   2. Run (in your project root):
//        flutterfire configure --project=<your-firebase-project-id>
//
//   3. This will generate the real firebase_options.dart and place
//      google-services.json (Android) + GoogleService-Info.plist (iOS)
//      in the correct locations automatically.
//
//   4. Then update main.dart to pass the options:
//        await Firebase.initializeApp(
//          options: DefaultFirebaseOptions.currentPlatform,
//        );
// ─────────────────────────────────────────────────────────────────────────────
//
// Below is a TEMPLATE showing the structure. Replace all placeholder values
// with real ones from your Firebase Console → Project Settings → Your Apps.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── Replace these with your real values ──────────────────────────────────

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: '1:YOUR_PROJECT_NUMBER:android:YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: '1:YOUR_PROJECT_NUMBER:ios:YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.yourcompany.veggieVendorApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: '1:YOUR_PROJECT_NUMBER:web:YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    authDomain: 'YOUR_PROJECT_ID.firebaseapp.com',
  );
}
